# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # - ALLOW_EMPTY_PASSWORD: yes
      - 'POSTGRESQL_PORT_NUMBER=5432'
      - 'POSTGRESQL_USERNAME=admin'
      - 'POSTGRESQL_PASSWORD=admin'
      - 'POSTGRESQL_DATABASE=linkmory'

volumes:
  postgresql_data:
    driver: local